### ISSUE TITLE
"folder_exclude_patterns" does not seem to work.

### ISSUE THREAD

**Issue by hdavidzhu** [willbeaufoy/DirectorySettings#3]
```
{
  "folder_exclude_patterns": ["platforms"],
  "font_size": 12
}
```

I have something like this. When I save, the `folder_exclude_patterns` don't kick in. However, `font_size` works perfectly and rescales.

**Comment by davepeck** [comment]
Thanks for the report, @hdavidzhu.

Are you using Sublime 2, or 3?

**Comment by hdavidzhu** [comment]
3

**Comment by hdavidzhu** [comment]
@davepeck would this be an easy or difficult feature to implement? I don't have too much bandwidth to learn the details of Sublime plugin creation, but this would help me a lot with files I want to exclude locally but not globally. Thanks!

**Comment by davepeck** [comment]
I don't know but I have it on my list! :-)

**Comment by davepeck** [comment]
@hdavidzhu FYI, at this point I'm 100% on the Atom editor and have little motivation to maintain this project. Would you be interested?

**Comment by hdavidzhu** [comment]
@davepeck haha funny that you say that because at this point, I'm _also_ on the Atom editor.

**Comment by mattlubner** [comment]
Looks like `folder_exclude_patterns` doesn't apply to the sidebar on a per-directory level… 😟

Any chance of this getting a fix / adding support for applying directory-level settings to the sidebar view?
