### ISSUE TITLE
Directory Settings replacement

### ISSUE THREAD

**Issue by TobyGiacometti** [willbeaufoy/DirectorySettings#5]
Since this package has not been worked on in the last 7 years, I was wondering whether you would mind if it is replaced by a newer package (https://github.com/wbond/package_control_channel/pull/8187). Do you have any objections or concerns?

**Comment by willbeaufoy** [comment]
Hi, yes I don't have any plans to work on this package any more, so sounds like a good idea to replace it.

**Comment by TobyGiacometti** [comment]
Thanks for your feedback!
